###
GET http://localhost:8080/healthy

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "PC Gamer",
  "price": 4999.99
}

###
GET http://localhost:8080/products/2

###
GET http://localhost:8080/products
